name: marlin_auto_build

on:
  push:
    paths:
      - 'builds/**'
  schedule:
    - cron:  '30 3 * * *'
  workflow_dispatch:

jobs:
  create_builds:
    runs-on: ubuntu-latest
    steps:
    - uses: raultrombin/marlin_auto_build@master